enum PSTATE {
    BLOB,
    NORMAL,
    DASHING,
    HURT,
    DEAD
}

enum ESTATE {
    IDLE,
    PATROL,
    ALERT,
    ATTACK,
    HURT,
    DEAD,
    FLEE
}

#macro LAYER_TILES     "MainTiles"
#macro LAYER_INSTANCES "Instances"
#macro LAYER_BG        "Background"

#macro PLAYER_MOVE_SPEED 4
#macro PLAYER_BLOB_SPEED 3
#macro PLAYER_DUCK_SPEED 1.75
#macro PLAYER_JUMP_FORCE -12
#macro PLAYER_DOUBLE_JUMP_FORCE -14.5
#macro PLAYER_GRAVITY 0.5
#macro PLAYER_FALL_CAP 20
#macro PLAYER_DASH_SPEED 12
#macro PLAYER_DASH_FRAMES 10
#macro PLAYER_DASH_COOLDOWN_FRAMES 24
#macro PLAYER_INVULN_FRAMES 30
#macro PLAYER_ATTACK_COOLDOWN 18
#macro PLAYER_ATTACK_DAMAGE 20
#macro PLAYER_BLOB_ATTACK_ANIM_FRAMES 36
#macro PLAYER_HUMANOID_ATTACK_ANIM_FRAMES 18
#macro PLAYER_SHOOT_COOLDOWN 14
#macro PLAYER_SHOT_DAMAGE 12
#macro PLAYER_SHOT_SPEED 10
#macro PLAYER_SHOT_LIFE_FRAMES 72
#macro PLAYER_PROJECTILE_VISUAL_SCALE 1.55
#macro ENEMY_PROJECTILE_VISUAL_SCALE 1.55
#macro CAMERA_VIEW_W 1366
#macro CAMERA_VIEW_H 768
#macro CAMERA_LOOKAHEAD_X 120
#macro CAMERA_FOLLOW_LERP 0.18
#macro ROOM_TRANSITION_FADE_FRAMES 16

#macro ENEMY_KNOCKBACK_X 4
#macro ENEMY_KNOCKBACK_Y -3
#macro ENEMY_HURT_FRAMES 10

#macro PICKUP_HEALTH_AMOUNT 25
#macro PICKUP_ENERGY_AMOUNT 25
#macro KILL_ENERGY_GAIN 20

#macro SAVE_FILE "amorphous_save.json"
#macro MEMORY_FRAGMENT_COUNT 4
