direction_facing = 1;
damage = 20;
life_frames = 10;
range_scale = 1.0;
sprite_index = spr_boss_melee_hit;
mask_index = spr_boss_melee_hit;
visible = true;
image_alpha = 0.32;
image_blend = make_color_rgb(255, 80, 80);
